var sgFixtureData = {
  prototype: {
    generatedAt: "2026-08-26 18:40",
    note: "静态原型使用只读核实后的 Windows 路径 fixture；不会调用生产后端。",
  },
  initialWorkspace: {
    name: "ozdqp-skill-hub",
    path: "E:\\ozdqp-skill-hub",
    summary: "已整理出 1 个推荐项目方案：3 个 Skill 与 1 个规则入口",
  },
  complexWorkspace: {
    name: "ozdqp-main-fix",
    path: "E:\\ozdqp-main-fix",
    summary: "发现 7 类内容与来源；已把可纳入内容、私有扩展和参考证据分开",
    facts: [
      "分析只读取文件、Git index 与链接关系",
      "检测到用户现有改动；全程保留，不清理",
      "项目私有内容默认留在工作区",
    ],
  },
  initialSystems: [
    {
      id: "ozdqp-project",
      name: "OZDQP Unity 项目方案",
      subtitle: "适用于 OZDQP Unity 项目的开发、UI 与 Git 规则",
      decision: "include",
      confidence: "活跃来源 · 结构清晰",
      skills: 3,
      rules: 1,
      badges: ["活跃来源", "3 个项目 Skill", "1 个规则入口"],
      explanation: "三个项目 Skill 由同一套 OZDQP 规则入口路由，已合并成一个可直接确认的项目方案。",
      sources: [
        { kind: "Skill 根", path: "E:\\ozdqp-skill-hub\\skills" },
        { kind: "规则入口", path: "E:\\ozdqp-skill-hub\\AGENTS.override.md" },
      ],
    },
  ],
  systems: [
    {
      id: "unity-rest",
      name: "UnitySkills REST",
      subtitle: "可纳入当前项目方案的 Unity Editor 操作组件",
      decision: "include",
      confidence: "高置信归并",
      skills: 71,
      rules: 1,
      badges: ["活跃来源", "Junction 别名", "缓存已排除"],
      explanation: "根目录入口是指向 baloot_client 活跃源的 Junction；PackageCache 2.0.8 拥有相同模块路径但内容版本不同，因此作为镜像证据折叠展示。",
      sources: [
        { kind: "真实来源", path: "E:\\ozdqp-main-fix\\baloot_client\\.agents\\skills\\unity-skills" },
        { kind: "Junction 别名", path: "E:\\ozdqp-main-fix\\.agents\\skills\\unity-skills" },
        { kind: "缓存镜像 2.0.8", path: "E:\\ozdqp-main-fix\\baloot_client\\Library\\PackageCache\\com.besty.unity-skills@65f1dc9500\\unity-skills~" },
      ],
    },
    {
      id: "unity-mcp",
      name: "Unity MCP CLI",
      subtitle: "同一后端面向多个 Agent 宿主的投影",
      decision: "include",
      confidence: "77 个完全重复 · Claude 有 62 个内容差异",
      skills: 78,
      rules: 3,
      badges: ["同后端家族", "多个宿主投影", "版本有差异"],
      explanation: ".agents / .cursor / .claude 分别有 78 / 78 / 64 个直接 Skill；前两者 77 个同名文件完全相同，Claude 投影有 62 个同名内容差异。",
      sources: [
        { kind: "Agent 投影", path: "E:\\ozdqp-main-fix\\baloot_client\\.agents\\skills" },
        { kind: "Cursor 投影", path: "E:\\ozdqp-main-fix\\baloot_client\\.cursor\\skills" },
        { kind: "Claude 投影", path: "E:\\ozdqp-main-fix\\baloot_client\\.claude\\skills" },
      ],
    },
    {
      id: "project-rules",
      name: "项目规则入口",
      subtitle: "根规则与 docs 子系统规则",
      decision: "keep-private",
      confidence: "4 个规则入口 · 根 AGENTS.md 有用户改动",
      skills: 0,
      rules: 4,
      badges: ["AGENTS.md", "CLAUDE.md", "用户改动", "需逐项确认"],
      explanation: "规则入口属于真实分析结果，但根 AGENTS.md 当前有用户脏改。默认只比较，不自动覆盖或纳入。",
      sources: [
        { kind: "根规则（已修改）", path: "E:\\ozdqp-main-fix\\AGENTS.md" },
        { kind: "Claude 规则", path: "E:\\ozdqp-main-fix\\CLAUDE.md" },
        { kind: "子系统规则", path: "E:\\ozdqp-main-fix\\docs\\systems\\merge2-minigame\\AGENTS.md" },
        { kind: "子系统规则", path: "E:\\ozdqp-main-fix\\docs\\systems\\backpack-store\\AGENTS.md" },
      ],
    },
    {
      id: "ai-testing",
      name: "AIGameTesting 项目私有扩展",
      subtitle: "项目内的自动化游戏测试 Skill",
      decision: "keep-private",
      confidence: "用途独立 · 可能含项目私有内容",
      skills: 1,
      rules: 0,
      badges: ["项目私有扩展", "默认不入库", "默认不上传"],
      explanation: "路径和用途均与通用 Unity 组件不同。默认保留在项目中，只有明确选择后才纳入某个项目方案。",
      sources: [
        { kind: "项目来源", path: "E:\\ozdqp-main-fix\\baloot_client\\Tools\\AIGameTesting\\agent_skills\\enter-game-hall" },
      ],
    },
    {
      id: "dormant",
      name: "Git 中的休眠项目 Skill",
      subtitle: "Git 有记录，但工作区当前没有物理文件",
      decision: "reference-only",
      confidence: "休眠 / 隐藏记录",
      skills: 331,
      rules: 2,
      badges: ["Git 休眠标记", "物理缺失", "只作证据"],
      explanation: "Git index 有 571 个 skip-worktree 条目，物理存在数为 0；其中 .agents / .claude / .codex 分别有 120 / 85 / 126 个隐藏 SKILL.md。",
      sources: [
        { kind: "Git index", path: "E:\\ozdqp-main-fix\\.agents + .claude + .codex（571 条）" },
      ],
    },
    {
      id: "declared-missing",
      name: "清单声明但未落盘",
      subtitle: "根 skills-lock.json 中有 2 个声明，磁盘没有对应内容",
      decision: "reference-only",
      confidence: "需要来源确认",
      skills: 2,
      rules: 0,
      badges: ["声明存在", "文件未找到", "不自动下载"],
      explanation: "保留声明与来源线索，等待用户确认；不会把不存在的 Skill 计为方案内容。",
      sources: [
        { kind: "声明入口", path: "E:\\ozdqp-main-fix\\skills-lock.json" },
        { kind: "未落盘", path: "game-performance-profiler · markdown-tables" },
      ],
    },
    {
      id: "cache-backup",
      name: "缓存与备份",
      subtitle: "PackageCache、本地缓存与旧 overlay 备份",
      decision: "reference-only",
      confidence: "只展示来源与保全边界",
      skills: 0,
      rules: 0,
      badges: ["Library/PackageCache", ".pytest_cache", "旧 overlay", "默认排除"],
      explanation: "缓存和备份可能帮助解释来源，但不是项目方案内容；默认不参与融合，也不清理。",
      sources: [
        { kind: "Unity 缓存", path: "E:\\ozdqp-main-fix\\baloot_client\\Library\\PackageCache（69 个包目录）" },
        { kind: "测试缓存", path: "E:\\ozdqp-main-fix\\.pytest_cache（3 个缓存文件）" },
        { kind: "旧 overlay 备份", path: "E:\\ozdqp-main-fix\\.codex\\local-overlay.pre-hub-20260818-181256" },
      ],
    },
  ],
  centralSystems: [
    { id: "ozdqp-dev", name: "OZDQP Unity 项目方案", skills: 3, rules: 1, source: "E:\\ozdqp-skill-hub · E:\\ozdqp-main-fix", status: "当前主方案" },
  ],
  versions: [
    { version: "v3", date: "今天 19:18", title: "纳入已连接工作区的新变化", changes: "+1 Skill · 2 项更新 · 1 个私有扩展保留", source: "E:\\ozdqp-main-fix" },
    { version: "v2", date: "今天 18:42", title: "补全 OZDQP Unity 项目方案", changes: "+2 方案组件 · 3 个文件更新 · 2 个冲突已解决", source: "E:\\ozdqp-main-fix" },
    { version: "v1", date: "今天 17:20", title: "创建 OZDQP Unity 项目方案", changes: "1 个项目方案 · 3 个 Skill · 1 个规则入口", source: "E:\\ozdqp-skill-hub" },
  ],
  upstreamUpdate: {
    workspace: "E:\\ozdqp-main-fix",
    plan: "OZDQP Unity 项目方案",
    currentPlanVersion: 2,
    workspaceVersion: 2,
    summary: "3 个 Skill、4 个文件有修改",
    skills: [
      {
        id: "tool-list",
        name: "tool-list",
        path: ".cursor\\skills\\tool-list",
        status: "新增",
        files: 1,
        additions: 42,
        deletions: 0,
        summary: "新增统一的工具发现与选择说明，让 Agent 先确认可用工具再执行任务。",
        difference: "当前方案中没有这个 Skill；工作区新增了完整的 SKILL.md。",
        highlights: ["新增工具搜索步骤", "补充无可用工具时的降级方式"],
      },
      {
        id: "unity-mcp-cli",
        name: "unity-mcp-cli",
        path: ".agents\\skills\\unity-mcp-cli",
        status: "已修改",
        files: 2,
        additions: 18,
        deletions: 7,
        summary: "重新整理安装和验证步骤，新同事可以按顺序完成 Unity MCP CLI 接入。",
        difference: "当前版本只有安装命令；工作区版本增加前置检查、验证结果和失败处理。",
        highlights: ["安装步骤由 2 步改为 4 步", "新增连接状态验证"],
      },
      {
        id: "ozdqp-development",
        name: "ozdqp-development",
        path: ".agents\\skills\\ozdqp-development",
        status: "已修改",
        files: 1,
        additions: 6,
        deletions: 2,
        summary: "收紧完成门禁，要求更新 Skill 后提供文件级差异和当前轮验证证据。",
        difference: "当前规则只要求说明结果；工作区版本明确要求逐文件审阅后再合并。",
        highlights: ["新增逐文件审阅门禁", "明确 AI 修改仍需人工确认"],
      },
    ],
    files: [
      {
        id: "tool-list-skill",
        skill: "tool-list",
        status: "新增",
        path: "skills/tool-list/SKILL.md",
        additions: 42,
        deletions: 0,
        diff: [
          { oldNo: "", newNo: "1", type: "add", text: "---" },
          { oldNo: "", newNo: "2", type: "add", text: "name: tool-list" },
          { oldNo: "", newNo: "3", type: "add", text: "description: 查找并选择当前任务可用的工具" },
          { oldNo: "", newNo: "4", type: "add", text: "---" },
          { oldNo: "", newNo: "5", type: "add", text: "# 工具选择" },
          { oldNo: "", newNo: "6", type: "add", text: "1. 先列出与任务直接相关的工具。" },
          { oldNo: "", newNo: "7", type: "add", text: "2. 优先使用专用工具，再使用通用工具。" },
          { oldNo: "", newNo: "8", type: "add", text: "3. 没有合适工具时说明降级方式。" },
        ],
        finalContent: "---\nname: tool-list\ndescription: 查找并选择当前任务可用的工具\n---\n\n# 工具选择\n\n1. 先列出与任务直接相关的工具。\n2. 优先使用专用工具，再使用通用工具。\n3. 没有合适工具时说明降级方式。\n4. 执行前确认工具不会越过用户授权边界。",
        changedLines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
        aiEdit: { line: 10, text: "3. 没有合适工具时，说明降级方式和未覆盖能力。" },
      },
      {
        id: "unity-mcp-skill",
        skill: "unity-mcp-cli",
        status: "修改",
        path: "skills/unity-mcp-cli/SKILL.md",
        additions: 10,
        deletions: 4,
        diff: [
          { oldNo: "8", newNo: "8", type: "context", text: "# 安装" },
          { oldNo: "9", newNo: "", type: "remove", text: "执行内部安装流程。" },
          { oldNo: "", newNo: "9", type: "add", text: "1. 确认 Node.js 与 Unity Editor 已安装。" },
          { oldNo: "", newNo: "10", type: "add", text: "2. 在项目根目录运行安装命令。" },
          { oldNo: "", newNo: "11", type: "add", text: "3. 返回 Skill Graft 检查连接状态。" },
          { oldNo: "12", newNo: "12", type: "context", text: "npm run install:unity-mcp" },
        ],
        finalContent: "---\nname: unity-mcp-cli\ndescription: 安装并验证 Unity MCP CLI\n---\n\n# 安装\n\n1. 确认 Node.js 与 Unity Editor 已安装。\n2. 在项目根目录运行 `npm run install:unity-mcp`。\n3. 返回 Skill Graft，确认工作区显示“已连接”。\n4. 打开 Unity Console，确认没有新的连接错误。",
        changedLines: [3, 8, 9, 10, 11],
        aiEdit: { line: 10, text: "3. 返回 Skill Graft，确认工作区显示“已连接”并记录验证时间。" },
      },
      {
        id: "unity-mcp-install",
        skill: "unity-mcp-cli",
        status: "修改",
        path: "skills/unity-mcp-cli/references/install.md",
        additions: 8,
        deletions: 3,
        diff: [
          { oldNo: "3", newNo: "3", type: "context", text: "## 连接验证" },
          { oldNo: "4", newNo: "", type: "remove", text: "运行 health 命令。" },
          { oldNo: "", newNo: "4", type: "add", text: "1. 运行 `unity-mcp health`。" },
          { oldNo: "", newNo: "5", type: "add", text: "2. 确认返回项目路径和 Editor 版本。" },
          { oldNo: "", newNo: "6", type: "add", text: "3. 连接失败时保留原配置并查看诊断。" },
        ],
        finalContent: "# Unity MCP CLI 安装参考\n\n## 连接验证\n\n1. 运行 `unity-mcp health`。\n2. 确认返回当前项目路径和 Unity Editor 版本。\n3. 回到 Skill Graft 查看工作区连接状态。\n4. 连接失败时保留原配置并打开高级诊断。",
        changedLines: [3, 5, 6, 7, 8],
        aiEdit: { line: 8, text: "4. 连接失败时保留原配置，打开高级诊断并复制错误摘要。" },
      },
      {
        id: "development-rule",
        skill: "ozdqp-development",
        status: "修改",
        path: "rules/AGENTS.override.md",
        additions: 6,
        deletions: 2,
        diff: [
          { oldNo: "20", newNo: "20", type: "context", text: "## 更新 Skill" },
          { oldNo: "21", newNo: "", type: "remove", text: "完成后说明修改结果。" },
          { oldNo: "", newNo: "21", type: "add", text: "先展示每个文件的差异和最终内容。" },
          { oldNo: "", newNo: "22", type: "add", text: "人工确认后才可合并到中心库。" },
          { oldNo: "", newNo: "23", type: "add", text: "AI 再修改后必须重新进入待确认状态。" },
        ],
        finalContent: "# OZDQP 项目规则\n\n## 更新 Skill\n\n1. 先展示每个文件的差异和最终内容。\n2. 人工确认后才可合并到中心库。\n3. AI 再修改后必须重新进入待确认状态。\n4. 合并会生成新方案版本，不覆盖历史。",
        changedLines: [3, 5, 6, 7, 8],
        aiEdit: { line: 7, text: "3. AI 或人工再次修改后，文件必须重新进入待确认状态。" },
      },
    ],
  },
};
