#!/usr/bin/env node
import fs from 'node:fs'
import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { HubCommand, InboxDecisionAction, SessionRequestOptions, SessionStatus, Sha256Identifier } from '../contracts/index.js'
import { createLocalHookDiagnosticAdapter } from '../adapters/local-hook-diagnostics.js'
import { createInstallHost } from '../adapters/install-host.js'
import { projectLegacyResult } from '../local/compat/legacy-projector.js'
import { createLocalHost, type LocalHost } from '../local/create-local-host.js'
import {
  formatDoctorReport,
  formatPurgeReport,
  formatSetupReport,
  formatUninstallReport,
  formatUpgradeReport,
  PRODUCT_ALIAS,
  PRODUCT_COMMAND
} from '../local/lifecycle/install-domain.js'
import { runDaemon } from './daemon.js'
import { acquireDaemonRunLifecycleGuard, daemonStatus, doctorHub, purgeHub, readDaemonLifecycleReceiptAuthority, resolveDataRoot, setupHub, startDaemonDetached, stopDaemonGuarded, uninstallHub, upgradeHub } from './install.js'

function print(value: unknown) {
  process.stdout.write(`${JSON.stringify(value, null, 2)}\n`)
}

function fail(message: string, code = 1): never {
  process.stderr.write(`${message}\n`)
  process.exit(code)
}

function usage(): string {
  return [
    `${PRODUCT_COMMAND} <command>          (also: ${PRODUCT_ALIAS})`,
    '  Business commands accept [--request-id <id>]; omitted IDs are generated by the Local host.',
    '  Business commands emit the versioned Application envelope by default.',
    '  Add --legacy-output for the deprecated v0 projection; --contract-v1 remains an accepted alias for the default.',
    '',
    'Install:',
    '  setup [--dry-run] [--json] [--no-daemon] [--no-path] [--no-task]',
    '                                 One-click: env, sg on PATH, silent keep-alive, logon autostart',
    '  uninstall [--json]             Remove sg, PATH entry, logon task, and the daemon',
    '  upgrade [--dry-run] [--json] [--no-daemon]',
    '                                 Atomically switch an owned installation to this package',
    '  purge --data-root <absolute> --dry-run',
    '  purge --data-root <absolute> --commit --data-root-id <id> --plan-hash <sha256:id>',
    '                                 Explicitly remove marker-owned user data after uninstall',
    '  doctor [--json]                Check Node/Git/Codex, sg, autostart, and API health',
    '  daemon start|stop|status|run   Keep-alive supervisor for the local HTTP API',
    '',
    'Query:',
    '  status                         Hub inventory, inbox counts, linked game repo',
    '  inbox list                     Canonical inbox inventory query (same Application status data)',
    '  inbox show --path <rel>        Read one inbox Skill through Application',
    '  list-worktrees                 Discover client worktrees under scan-roots',
    '  list-skills                    Resident / adopted / inbox nodes',
    '  inspect-schema                 Inspect shared Hub state schema/runtime compatibility',
    '  snapshot create|list           Capture or list committed immutable library snapshots',
    '  snapshot show --id <sha256:id> Show one committed snapshot manifest',
    '  pin show --worktree <path>     Show the claimed worktree pin without materializing it',
    '  pin set --worktree <path> --snapshot <sha256:id> [--skill <name> ... | --clear-skills]',
    '                                 Update only requestedSnapshot/selectedSkills; never copy files',
    '  plan-sync --worktree <path>    Produce a zero-write copy/materialization plan',
    '  claim --worktree <path> --snapshot <sha256:id> --session-id <id>',
    '        [--skill <name> ... | --clear-skills]',
    '                                 Claim only after a successful confirmed attach session',
    '  sync --worktree <path> --plan-hash <sha256:id> [--session-id <id>]',
    '                                 Execute only the freshly revalidated copy plan',
    '  migrate-legacy --worktree <path> --dry-run',
    '  migrate-legacy --worktree <path> --commit --plan-hash <sha256:id>',
    '  rollback-legacy --worktree <path> --migration-id <sha256:id> --dry-run',
    '  rollback-legacy --worktree <path> --migration-id <sha256:id> --commit --plan-hash <sha256:id>',
    '  migrate-state --dry-run        Produce and audit a deterministic V1 -> V2 migration plan',
    '  migrate-state --commit --plan-hash <sha256:id>',
    '                                 Commit only the exact current migration plan',
    '',
    'Disk (via CLI; first-time attach is a session, not a silent rewrite):',
    '  repair-links --worktree <path> Repair links on an already-attached tree',
    '  apply-legacy-attach --worktree <path> [--session-id <id>] [--source-policy requireMatch|preferLibrary|promoteFromWorktree]',
    '                                 [--visibility disable|preserve] [--configure-git]',
    '                                 Complete a confirmed legacy attach through Application v1.',
    '  apply-legacy-detach --worktree <path> [--session-id <id>]',
    '                                 Complete a confirmed legacy detach through Application v1.',
    '  ingest [--game-repo <path>] [--dispatch] [--dry-run]',
    '                                 Read hook payload on stdin; empty payload is a no-op',
    '  decide --id <id> --action adopt|merge|reject [--note <text>] [--merge-target <rel>]',
    '',
    'Sessions (background Codex; default model gpt-5.6-luna at max effort):',
    '  attach --worktree <path> [--intent <text>] [--model <id>] [--effort <level>] [--no-spawn] [--wait]',
    '                                 Enqueue and spawn a detached Codex attach conversation.',
    '                                 The conversation freezes a snapshot/selection handoff; after exit 0 use claim, plan-sync, then sync.',
    '                                 --no-spawn only records the session and cannot authorize a claim.',
    '                                 --wait blocks until the conversation settles (default returns immediately).',
    '  detach --worktree <path> [--intent <text>] [--no-spawn] [--wait]',
    '  edit --path <rel> [--intent <text>] [--no-spawn] [--wait]',
    '  chat [--intent <text>] [--worktree <path>] [--no-spawn] [--wait]',
    '  analyze [--id <inbox-id>] [--intent <text>] [--no-spawn] [--wait]',
    '                                 Enqueue an analysis session; on finish writes suggestion.* and status=proposed.',
    '  resume --id <id> --message <text> [--no-spawn] [--wait]',
    '  cancel --id <id> [--reason <text>]',
    '                                 Request cancellation and return the durable session state',
    '  session list [--status <status> ...]',
    '  session show --id <id> [--wait]',
    '  session --id <id> [--wait]     Deprecated alias for session show',
    '',
    'Hook diagnostics (host-local, locator-free output):',
    '  hook-diagnostic --worktree <path> --hook post-checkout|reference-transaction',
    '                  --phase launch|command --code NODE_UNAVAILABLE|CLI_MISSING|COMMAND_FAILED',
    '                  [--exit-code 1..255] [--request-id <id>]'
  ].join('\n')
}

function findHubRoot(): string {
  const here = dirname(fileURLToPath(import.meta.url))
  return dirname(dirname(here))
}

function takeFlag(argv: string[], name: string): string | undefined {
  const index = argv.indexOf(name)
  if (index < 0) return undefined
  const value = argv[index + 1]
  if (!value || value.startsWith('-')) fail(`${name} requires a value`)
  argv.splice(index, 2)
  return value
}

function takeSwitch(argv: string[], name: string): boolean {
  const index = argv.indexOf(name)
  if (index < 0) return false
  argv.splice(index, 1)
  return true
}

function takeRepeatedFlags(argv: string[], name: string): string[] {
  const values: string[] = []
  for (;;) {
    const value = takeFlag(argv, name)
    if (value === undefined) return values
    values.push(value)
  }
}

function requireNoArguments(argv: string[], commandName: string): void {
  if (argv.length > 0) fail(`${commandName} received unsupported or duplicate arguments`)
}

function readStdin(): string {
  if (process.stdin.isTTY) return ''
  try {
    return fs.readFileSync(0, 'utf8')
  } catch {
    return ''
  }
}

async function executeProjected(host: LocalHost, command: HubCommand): Promise<unknown> {
  const result = await host.application.execute(command)
  return projectLegacyResult(result, host)
}

async function reapSessionState(
  host: LocalHost,
  sessionId?: string,
  transport = 'cli'
): Promise<void> {
  const scope = sessionId ? [sessionId] : undefined
  if (host.localSessions && !host.localSessions.needsReap(scope)) return
  await executeProjected(host, {
    kind: 'reapSessions',
    meta: host.commandMeta(transport),
    sessionIds: scope
  })
}

async function getSessionResult(host: LocalHost, id: string, requestId?: string, typed = false): Promise<unknown> {
  const result = await host.application.execute({
    kind: 'getSession',
    meta: host.commandMeta('cli', requestId),
    sessionId: id
  })
  return typed ? result : projectLegacyResult(result, host)
}

function sessionState(value: unknown): { id: string; status: string } {
  const result = value as {
    data?: { session?: { id?: unknown; status?: unknown } }
    session?: { id?: unknown; status?: unknown }
  } | null
  const session = result?.data?.session || result?.session
  if (!session || typeof session.id !== 'string' || typeof session.status !== 'string') {
    throw new Error('session response is missing session state')
  }
  return { id: session.id, status: session.status }
}

async function waitUntilSettled(host: LocalHost, id: string, requestId?: string, typed = false): Promise<unknown> {
  const timeoutMs = Number(process.env.HUB_WAIT_TIMEOUT_MS || 30 * 60 * 1000)
  const started = Date.now()
  let nextRequestId = requestId
  for (;;) {
    await reapSessionState(host, id)
    const response = await getSessionResult(host, id, nextRequestId, typed)
    nextRequestId = undefined
    const session = sessionState(response)
    if (session.status !== 'running') return response
    if (Date.now() - started > timeoutMs) fail(`session ${id} still running after ${timeoutMs}ms`)
    await new Promise((resolve) => setTimeout(resolve, 250))
  }
}

function takeRunnerOptions(argv: string[]): SessionRequestOptions {
  const profile = takeFlag(argv, '--model')
  const quality = takeFlag(argv, '--effort')
  const noSpawn = takeSwitch(argv, '--no-spawn')
  const wait = takeSwitch(argv, '--wait')
  return { profile, quality, start: !noSpawn, wait }
}

const rawArgv = process.argv.slice(2)
const command = rawArgv[0] || ''
if (!command || command === '-h' || command === '--help') {
  process.stdout.write(`${usage()}\n`)
  process.exit(command ? 0 : 1)
}

const argv = rawArgv.slice(1)
const packageRoot = findHubRoot()

async function main() {
  if (command === 'setup' || command === 'install') {
    const flags = {
      dryRun: takeSwitch(argv, '--dry-run'),
      json: takeSwitch(argv, '--json'),
      noDaemon: takeSwitch(argv, '--no-daemon'),
      noPath: takeSwitch(argv, '--no-path'),
      noTask: takeSwitch(argv, '--no-task'),
      rebuild: takeSwitch(argv, '--rebuild')
    }
    requireNoArguments(argv, command)
    const result = await setupHub(packageRoot, flags)
    if (flags.json) print(result)
    else process.stdout.write(`${formatSetupReport(result)}\n`)
    if (!result.ok) process.exitCode = 1
    return
  }
  if (command === 'uninstall') {
    const json = takeSwitch(argv, '--json')
    requireNoArguments(argv, 'uninstall')
    const result = await uninstallHub(packageRoot)
    if (json) print(result)
    else process.stdout.write(`${formatUninstallReport(result)}\n`)
    if (!result.ok) process.exitCode = 1
    return
  }
  if (command === 'doctor') {
    const json = takeSwitch(argv, '--json')
    requireNoArguments(argv, 'doctor')
    const report = await doctorHub(packageRoot)
    if (json) print(report)
    else process.stdout.write(`${formatDoctorReport(report)}\n`)
    if (!report.ok) process.exitCode = 1
    return
  }
  if (command === 'upgrade') {
    const flags = {
      dryRun: takeSwitch(argv, '--dry-run'),
      json: takeSwitch(argv, '--json'),
      noDaemon: takeSwitch(argv, '--no-daemon')
    }
    requireNoArguments(argv, 'upgrade')
    const result = await upgradeHub(packageRoot, flags)
    if (flags.json) print(result)
    else process.stdout.write(`${formatUpgradeReport(result)}\n`)
    if (!result.ok) process.exitCode = 1
    return
  }
  if (command === 'purge') {
    const dataRoot = takeFlag(argv, '--data-root')
    if (!dataRoot) fail('purge requires --data-root')
    const flags = {
      dataRoot,
      dryRun: takeSwitch(argv, '--dry-run'),
      commit: takeSwitch(argv, '--commit'),
      planHash: takeFlag(argv, '--plan-hash') as `sha256:${string}` | undefined,
      dataRootId: takeFlag(argv, '--data-root-id'),
      json: takeSwitch(argv, '--json')
    }
    requireNoArguments(argv, 'purge')
    const result = await purgeHub(packageRoot, flags)
    if (flags.json) print(result)
    else process.stdout.write(`${formatPurgeReport(result)}\n`)
    if (!result.ok) process.exitCode = 1
    return
  }
  if (command === 'hook-diagnostic') {
    const worktree = takeFlag(argv, '--worktree')
    const rawHook = takeFlag(argv, '--hook')
    const rawPhase = takeFlag(argv, '--phase')
    const rawCode = takeFlag(argv, '--code')
    const hook = rawHook === 'post-checkout' || rawHook === 'reference-transaction' ? rawHook : undefined
    const phase = rawPhase === 'launch' || rawPhase === 'command' ? rawPhase : undefined
    const code = rawCode === 'NODE_UNAVAILABLE' || rawCode === 'CLI_MISSING' || rawCode === 'COMMAND_FAILED'
      ? rawCode
      : undefined
    const exitCodeText = takeFlag(argv, '--exit-code')
    const requestId = takeFlag(argv, '--request-id')
    requireNoArguments(argv, 'hook-diagnostic')
    const exitCode = exitCodeText === undefined || !/^\d{1,3}$/.test(exitCodeText)
      ? exitCodeText === undefined ? undefined : Number.NaN
      : Number(exitCodeText)
    let recorded = false
    const diagnosticShapeOk = code === 'COMMAND_FAILED'
      ? phase === 'command' && Number.isInteger(exitCode) && Number(exitCode) >= 1 && Number(exitCode) <= 255
      : phase === 'launch' && exitCode === undefined
    if (worktree && hook && phase && code && diagnosticShapeOk) {
      try {
        recorded = createLocalHookDiagnosticAdapter().record({ worktree, hook, phase, code, exitCode, requestId }).status === 'recorded'
      } catch { /* locator-free refusal below */ }
    }
    print({ ok: recorded, action: 'hook-diagnostic', recorded, code: code || 'DIAGNOSTIC_REFUSED' })
    if (!recorded) process.exitCode = 1
    return
  }

  const dataRoot = resolveDataRoot(packageRoot)
  if (command === 'daemon') {
    const sub = argv[0] || 'status'
    if (sub === 'run') {
      const installHost = createInstallHost()
      const guard = await acquireDaemonRunLifecycleGuard(packageRoot, dataRoot, installHost)
      try {
        await runDaemon({
          hubRoot: packageRoot,
          packageRoot,
          dataRoot,
          host: installHost,
          home: installHost.home,
          readReceiptAuthority: () => readDaemonLifecycleReceiptAuthority(dataRoot, installHost),
          onStartupRevalidate: guard.revalidate,
          releaseStartupAuthority: (terminalSeal) => guard.release(terminalSeal)
        })
      } finally {
        await guard.release()
      }
      return
    }
    if (sub === 'start') {
      const started = await startDaemonDetached(packageRoot, undefined, dataRoot)
      print({ action: 'daemon-start', ...started })
      if (!started.ok) process.exitCode = 1
      return
    }
    if (sub === 'stop') {
      const stopped = await stopDaemonGuarded(packageRoot, undefined, dataRoot)
      print({
        ok: stopped,
        action: 'daemon-stop',
        stopped,
        ...(stopped ? {} : {
          error: {
            code: 'DAEMON_INSTANCE_UNVERIFIED',
            message: 'daemon instance could not be verified stopped; lifecycle markers were preserved'
          }
        })
      })
      if (!stopped) process.exitCode = 1
      return
    }
    if (sub === 'status') {
      const status = await daemonStatus(packageRoot, undefined, dataRoot)
      print(status)
      if (!status.ok) process.exitCode = 1
      return
    }
    fail(`unknown daemon command: ${sub}\n${usage()}`)
  }

  const host = createLocalHost({ packageRoot, dataRoot })
  const requestId = takeFlag(argv, '--request-id')
  const explicitContractV1 = takeSwitch(argv, '--contract-v1')
  const legacyOutput = takeSwitch(argv, '--legacy-output')
  if (explicitContractV1 && legacyOutput) fail('--contract-v1 and --legacy-output are mutually exclusive')
  const contractV1 = !legacyOutput
  const commandMeta = () => host.commandMeta('cli', requestId)
  const execute = async (typed: HubCommand) => {
    const sessionId = typed.kind !== 'reapSessions'
      && 'sessionId' in typed
      && typeof typed.sessionId === 'string'
      && typed.sessionId
      ? typed.sessionId
      : undefined
    if (sessionId) await reapSessionState(host, sessionId, 'cli-session-reap')
    const result = await host.application.execute(typed)
    if (!result.ok) process.exitCode = 1
    if (contractV1) {
      return result
    }
    return projectLegacyResult(result, host)
  }

  if (command === 'status') {
    await reapSessionState(host)
    print(await execute({ kind: 'status', meta: commandMeta() }))
    return
  }
  if (command === 'inbox') {
    const subcommand = argv.shift()
    if (subcommand === 'list') {
      requireNoArguments(argv, 'inbox list')
      await reapSessionState(host)
      print(await execute({ kind: 'status', meta: commandMeta() }))
      return
    }
    if (subcommand === 'show') {
      const skillPath = takeFlag(argv, '--path')
      if (!skillPath) fail('inbox show requires --path')
      requireNoArguments(argv, 'inbox show')
      print(await execute({ kind: 'readSkill', meta: commandMeta(), path: skillPath }))
      return
    }
    fail('inbox requires list or show')
  }
  if (command === 'list-worktrees') {
    print(await execute({ kind: 'listWorktrees', meta: commandMeta() }))
    return
  }
  if (command === 'list-skills') {
    print(await execute({ kind: 'listSkills', meta: commandMeta() }))
    return
  }
  if (command === 'inspect-schema') {
    requireNoArguments(argv, 'inspect-schema')
    print(await execute({ kind: 'inspectSchema', meta: commandMeta() }))
    return
  }
  if (command === 'snapshot') {
    const subcommand = argv.shift()
    if (subcommand === 'create') {
      requireNoArguments(argv, 'snapshot create')
      print(await execute({ kind: 'createSnapshot', meta: commandMeta() }))
      return
    }
    if (subcommand === 'list') {
      requireNoArguments(argv, 'snapshot list')
      print(await execute({ kind: 'listSnapshots', meta: commandMeta() }))
      return
    }
    if (subcommand === 'show') {
      const snapshotId = takeFlag(argv, '--id') as Sha256Identifier | undefined
      if (!snapshotId) fail('snapshot show requires --id')
      requireNoArguments(argv, 'snapshot show')
      print(await execute({ kind: 'getSnapshot', meta: commandMeta(), snapshotId }))
      return
    }
    fail('snapshot requires create, list, or show')
  }
  if (command === 'pin') {
    const subcommand = argv.shift()
    const worktree = takeFlag(argv, '--worktree')
    if (!worktree) fail(`pin ${subcommand || ''} requires --worktree`.replace('  ', ' '))
    if (subcommand === 'show') {
      requireNoArguments(argv, 'pin show')
      print(await execute({ kind: 'getPin', meta: commandMeta(), worktree }))
      return
    }
    if (subcommand === 'set') {
      const snapshotId = takeFlag(argv, '--snapshot') as Sha256Identifier | undefined
      const selectedSkills = takeRepeatedFlags(argv, '--skill')
      const clearSkills = takeSwitch(argv, '--clear-skills')
      if (!snapshotId) fail('pin set requires --snapshot')
      if (clearSkills && selectedSkills.length > 0) {
        fail('pin set accepts either --skill or --clear-skills, not both')
      }
      requireNoArguments(argv, 'pin set')
      print(await execute({
        kind: 'setPin',
        meta: commandMeta(),
        worktree,
        snapshotId,
        ...(clearSkills ? { selectedSkills: [] } : selectedSkills.length > 0 ? { selectedSkills } : {})
      }))
      return
    }
    fail('pin requires show or set')
  }
  if (command === 'plan-sync') {
    const worktree = takeFlag(argv, '--worktree')
    if (!worktree) fail('plan-sync requires --worktree')
    requireNoArguments(argv, 'plan-sync')
    print(await execute({ kind: 'planSync', meta: commandMeta(), worktree }))
    return
  }
  if (command === 'claim') {
    const worktree = takeFlag(argv, '--worktree')
    const snapshotId = takeFlag(argv, '--snapshot') as Sha256Identifier | undefined
    const sessionId = takeFlag(argv, '--session-id')
    const selectedSkills = takeRepeatedFlags(argv, '--skill').sort()
    const clearSkills = takeSwitch(argv, '--clear-skills')
    if (!worktree || !snapshotId || !sessionId) {
      fail('claim requires --worktree, --snapshot, and --session-id')
    }
    if (clearSkills && selectedSkills.length > 0) {
      fail('claim accepts either --skill or --clear-skills, not both')
    }
    if (!clearSkills && selectedSkills.length === 0) {
      fail('claim requires at least one --skill or explicit --clear-skills')
    }
    requireNoArguments(argv, 'claim')
    print(await execute({
      kind: 'claimWorktree',
      meta: commandMeta(),
      worktree,
      snapshotId,
      selectedSkills: clearSkills ? [] : selectedSkills,
      sessionId
    }))
    return
  }
  if (command === 'sync') {
    const worktree = takeFlag(argv, '--worktree')
    const planHash = takeFlag(argv, '--plan-hash') as Sha256Identifier | undefined
    const sessionId = takeFlag(argv, '--session-id')
    if (!worktree || !planHash) fail('sync requires --worktree and --plan-hash')
    requireNoArguments(argv, 'sync')
    print(await execute({ kind: 'sync', meta: commandMeta(), worktree, planHash, sessionId }))
    return
  }
  if (command === 'migrate-legacy') {
    const worktree = takeFlag(argv, '--worktree')
    const dryRun = takeSwitch(argv, '--dry-run')
    const commit = takeSwitch(argv, '--commit')
    const planHash = takeFlag(argv, '--plan-hash') as Sha256Identifier | undefined
    if (!worktree) fail('migrate-legacy requires --worktree')
    if (dryRun === commit) fail('migrate-legacy requires exactly one of --dry-run or --commit')
    if (dryRun && planHash) fail('migrate-legacy --dry-run does not accept --plan-hash')
    if (commit && !planHash) fail('migrate-legacy --commit requires --plan-hash')
    requireNoArguments(argv, 'migrate-legacy')
    print(await execute(dryRun
      ? { kind: 'migrateLegacy', meta: commandMeta(), worktree, mode: 'dryRun' }
      : {
          kind: 'migrateLegacy',
          meta: commandMeta(),
          worktree,
          mode: 'commit',
          planHash: planHash as Sha256Identifier
        }))
    return
  }
  if (command === 'rollback-legacy') {
    const worktree = takeFlag(argv, '--worktree')
    const migrationId = takeFlag(argv, '--migration-id') as Sha256Identifier | undefined
    const dryRun = takeSwitch(argv, '--dry-run')
    const commit = takeSwitch(argv, '--commit')
    const planHash = takeFlag(argv, '--plan-hash') as Sha256Identifier | undefined
    if (!worktree || !migrationId) fail('rollback-legacy requires --worktree and --migration-id')
    if (dryRun === commit) fail('rollback-legacy requires exactly one of --dry-run or --commit')
    if (dryRun && planHash) fail('rollback-legacy --dry-run does not accept --plan-hash')
    if (commit && !planHash) fail('rollback-legacy --commit requires --plan-hash')
    requireNoArguments(argv, 'rollback-legacy')
    print(await execute(dryRun
      ? {
          kind: 'rollbackLegacyMigration',
          meta: commandMeta(),
          worktree,
          migrationId,
          mode: 'dryRun'
        }
      : {
          kind: 'rollbackLegacyMigration',
          meta: commandMeta(),
          worktree,
          migrationId,
          mode: 'commit',
          planHash: planHash as Sha256Identifier
        }))
    return
  }
  if (command === 'migrate-state') {
    const dryRun = takeSwitch(argv, '--dry-run')
    const commit = takeSwitch(argv, '--commit')
    const planHash = takeFlag(argv, '--plan-hash') as Sha256Identifier | undefined
    if (dryRun === commit) fail('migrate-state requires exactly one of --dry-run or --commit')
    if (dryRun && planHash) fail('migrate-state --dry-run does not accept --plan-hash')
    if (commit && !planHash) fail('migrate-state --commit requires --plan-hash')
    requireNoArguments(argv, 'migrate-state')
    print(await execute({
      kind: 'migrateState',
      meta: commandMeta(),
      mode: dryRun ? 'dryRun' : 'commit',
      ...(planHash ? { planHash } : {})
    }))
    return
  }
  if (command === 'repair-links') {
    const worktree = takeFlag(argv, '--worktree')
    if (!worktree) fail('repair-links requires --worktree')
    print(await execute({ kind: 'repairLegacy', meta: commandMeta(), worktree }))
    return
  }
  if (command === 'apply-legacy-attach') {
    const worktree = takeFlag(argv, '--worktree')
    const sessionId = takeFlag(argv, '--session-id')
    const sourcePolicy = takeFlag(argv, '--source-policy') as 'requireMatch' | 'preferLibrary' | 'promoteFromWorktree' | undefined
    const visibility = takeFlag(argv, '--visibility') as 'disable' | 'preserve' | undefined
    const configureGit = takeSwitch(argv, '--configure-git')
    if (!worktree) fail('apply-legacy-attach requires --worktree')
    print(await execute({
      kind: 'applyLegacyAttach',
      meta: commandMeta(),
      worktree,
      sessionId,
      sourcePolicy,
      visibility,
      configureGit
    }))
    return
  }
  if (command === 'apply-legacy-detach') {
    const worktree = takeFlag(argv, '--worktree')
    const sessionId = takeFlag(argv, '--session-id')
    if (!worktree) fail('apply-legacy-detach requires --worktree')
    print(await execute({
      kind: 'applyLegacyDetach',
      meta: commandMeta(),
      worktree,
      sessionId
    }))
    return
  }
  if (command === 'ingest') {
    const gameRepo = takeFlag(argv, '--game-repo')
    const dispatch = takeSwitch(argv, '--dispatch')
    const dryRun = takeSwitch(argv, '--dry-run')
    const payload = readStdin()
    print(await execute({
      kind: 'ingest',
      meta: commandMeta(),
      gameRepo,
      payload,
      dispatch,
      dryRun
    }))
    return
  }
  if (command === 'decide') {
    const id = takeFlag(argv, '--id')
    const action = takeFlag(argv, '--action') as InboxDecisionAction | undefined
    const note = takeFlag(argv, '--note')
    const mergeTarget = takeFlag(argv, '--merge-target')
    if (!id || !action) fail('decide requires --id and --action')
    print(await execute({ kind: 'decide', meta: commandMeta(), id, action, note, mergeTarget }))
    return
  }
  if (command === 'session') {
    const subcommand = argv[0] === 'list' || argv[0] === 'show' ? argv.shift() : undefined
    if (subcommand === 'list') {
      const statuses = takeRepeatedFlags(argv, '--status') as SessionStatus[]
      requireNoArguments(argv, 'session list')
      await reapSessionState(host)
      print(await execute({
        kind: 'listSessions',
        meta: commandMeta(),
        ...(statuses.length > 0 ? { statuses } : {})
      }))
      return
    }
    const id = takeFlag(argv, '--id')
    const wait = takeSwitch(argv, '--wait')
    if (!id) fail(subcommand === 'show' ? 'session show requires --id' : 'session requires --id')
    requireNoArguments(argv, subcommand === 'show' ? 'session show' : 'session')
    if (contractV1 && !wait) {
      await reapSessionState(host, id)
      print(await execute({ kind: 'getSession', meta: commandMeta(), sessionId: id }))
      return
    }
    const response = wait
      ? await waitUntilSettled(host, id, requestId, contractV1)
      : await (async () => {
          await reapSessionState(host, id)
          return contractV1
            ? execute({ kind: 'getSession', meta: commandMeta(), sessionId: id })
            : getSessionResult(host, id, requestId)
        })()
    print(response)
    return
  }
  if (command === 'analyze') {
    const inboxId = takeFlag(argv, '--id')
    const intent = takeFlag(argv, '--intent') || 'Analyze queued inbox skill updates'
    const runner = takeRunnerOptions(argv)
    print(await execute({ kind: 'analyze', meta: commandMeta(), inboxId, intent, runner }))
    return
  }
  if (command === 'attach' || command === 'detach' || command === 'edit' || command === 'chat') {
    const worktree = takeFlag(argv, '--worktree')
    const skillPath = takeFlag(argv, '--path')
    const intent = takeFlag(argv, '--intent')
    const runner = takeRunnerOptions(argv)
    if ((command === 'attach' || command === 'detach') && !worktree) fail(`${command} requires --worktree`)
    if (command === 'attach') {
      print(await execute({ kind: 'attach', meta: commandMeta(), worktree: worktree as string, intent, runner }))
      return
    }
    if (command === 'detach') {
      print(await execute({ kind: 'detach', meta: commandMeta(), worktree: worktree as string, intent, runner }))
      return
    }
    if (command === 'edit') {
      if (!skillPath) fail('edit requires --path')
      print(await execute({ kind: 'edit', meta: commandMeta(), path: skillPath, intent, runner }))
      return
    }
    print(await execute({ kind: 'chat', meta: commandMeta(), worktree, intent, runner }))
    return
  }
  if (command === 'resume') {
    const id = takeFlag(argv, '--id')
    const message = takeFlag(argv, '--message')
    const runner = takeRunnerOptions(argv)
    if (!id || !message) fail('resume requires --id and --message')
    print(await execute({
      kind: 'resumeSession',
      meta: commandMeta(),
      sessionId: id,
      message,
      runner
    }))
    return
  }
  if (command === 'cancel') {
    const id = takeFlag(argv, '--id')
    const reason = takeFlag(argv, '--reason')
    if (!id) fail('cancel requires --id')
    requireNoArguments(argv, 'cancel')
    print(await execute({
      kind: 'cancelSession',
      meta: commandMeta(),
      sessionId: id,
      reason
    }))
    return
  }
  fail(`unknown command: ${command}\n${usage()}`)
}

main().catch((error) => {
  fail(error instanceof Error ? error.message : String(error))
})
