#!/usr/bin/env node
import fs from 'node:fs'
import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { HubCommand, InboxDecisionAction, SessionRequestOptions, Sha256Identifier } from '../contracts/index.js'
import { projectLegacyResult } from '../local/compat/legacy-projector.js'
import { createLocalHost, type LocalHost } from '../local/create-local-host.js'
import { resolveLocalDataRoot } from '../local/data-root.js'
import { formatDoctorReport, formatSetupReport, formatUninstallReport, PRODUCT_ALIAS, PRODUCT_COMMAND } from '../local/lifecycle/install-domain.js'
import { runDaemon, stopDaemon } from './daemon.js'
import { daemonStatus, doctorHub, setupHub, startDaemonDetached, uninstallHub } from './install.js'

function print(value: unknown) {
  process.stdout.write(`${JSON.stringify(value, null, 2)}\n`)
}

function fail(message: string, code = 1): never {
  process.stderr.write(`${message}\n`)
  process.exit(code)
}

function usage(): string {
  return [
    `${PRODUCT_COMMAND} <command>          (also: ${PRODUCT_ALIAS})`,
    '  Business commands accept [--request-id <id>]; omitted IDs are generated by the Local host.',
    '  Add --contract-v1 to emit the versioned Application envelope instead of the legacy projection.',
    '  These command names are the deprecated v0 compatibility surface over Application contract v1.',
    '',
    'Install:',
    '  setup [--dry-run] [--json] [--no-daemon] [--no-path] [--no-task] [--rebuild]',
    '                                 One-click: env, sg on PATH, silent keep-alive, logon autostart',
    '  uninstall [--json]             Remove sg, PATH entry, logon task, and the daemon',
    '  doctor [--json]                Check Node/Git/Codex, sg, autostart, and API health',
    '  daemon start|stop|status|run   Keep-alive supervisor for the local HTTP API',
    '',
    'Query:',
    '  status                         Hub inventory, inbox counts, linked game repo',
    '  list-worktrees                 Discover client worktrees under scan-roots',
    '  list-skills                    Resident / adopted / inbox nodes',
    '  inspect-schema                 Inspect shared Hub state schema/runtime compatibility',
    '  snapshot create|list           Capture or list committed immutable library snapshots',
    '  snapshot show --id <sha256:id> Show one committed snapshot manifest',
    '  pin show --worktree <path>     Show the claimed worktree pin without materializing it',
    '  pin set --worktree <path> --snapshot <sha256:id> [--skill <name> ... | --clear-skills]',
    '                                 Update only requestedSnapshot/selectedSkills; never copy files',
    '  migrate-state --dry-run        Produce and audit a deterministic V1 -> V2 migration plan',
    '  migrate-state --commit --plan-hash <sha256:id>',
    '                                 Commit only the exact current migration plan',
    '',
    'Disk (via CLI; first-time attach is a session, not a silent rewrite):',
    '  repair-links --worktree <path> Repair links on an already-attached tree',
    '  apply-legacy-attach --worktree <path> [--session-id <id>] [--source-policy requireMatch|preferLibrary|promoteFromWorktree]',
    '                                 [--visibility disable|preserve] [--configure-git]',
    '                                 Complete a confirmed legacy attach through Application v1.',
    '  apply-legacy-detach --worktree <path> [--session-id <id>]',
    '                                 Complete a confirmed legacy detach through Application v1.',
    '  ingest [--game-repo <path>] [--dispatch] [--dry-run]',
    '                                 Read hook payload on stdin; empty payload is a no-op',
    '  decide --id <id> --action adopt|merge|reject [--note <text>] [--merge-target <rel>]',
    '',
    'Sessions (background Codex; default model gpt-5.6-luna at max effort):',
    '  attach --worktree <path> [--intent <text>] [--model <id>] [--effort <level>] [--no-spawn] [--wait]',
    '                                 Enqueue and spawn a detached Codex attach conversation.',
    '                                 Codex conversation does the first-time strip and link. --no-spawn only records the session.',
    '                                 --wait blocks until the conversation settles (default returns immediately).',
    '  detach --worktree <path> [--intent <text>] [--no-spawn] [--wait]',
    '  edit --path <rel> [--intent <text>] [--no-spawn] [--wait]',
    '  chat [--intent <text>] [--worktree <path>] [--no-spawn] [--wait]',
    '  analyze [--id <inbox-id>] [--intent <text>] [--no-spawn] [--wait]',
    '                                 Enqueue an analysis session; on finish writes suggestion.* and status=proposed.',
    '  resume --id <id> --message <text> [--no-spawn] [--wait]',
    '  session --id <id> [--wait]     Read the same skill-review/sessions.json; reap a dead pid first'
  ].join('\n')
}

function findHubRoot(): string {
  const here = dirname(fileURLToPath(import.meta.url))
  return dirname(dirname(here))
}

function takeFlag(argv: string[], name: string): string | undefined {
  const index = argv.indexOf(name)
  if (index < 0) return undefined
  const value = argv[index + 1]
  if (!value || value.startsWith('-')) fail(`${name} requires a value`)
  argv.splice(index, 2)
  return value
}

function takeSwitch(argv: string[], name: string): boolean {
  const index = argv.indexOf(name)
  if (index < 0) return false
  argv.splice(index, 1)
  return true
}

function takeRepeatedFlags(argv: string[], name: string): string[] {
  const values: string[] = []
  for (;;) {
    const value = takeFlag(argv, name)
    if (value === undefined) return values
    values.push(value)
  }
}

function requireNoArguments(argv: string[], commandName: string): void {
  if (argv.length > 0) fail(`${commandName} received unsupported or duplicate arguments`)
}

function readStdin(): string {
  if (process.stdin.isTTY) return ''
  try {
    return fs.readFileSync(0, 'utf8')
  } catch {
    return ''
  }
}

async function executeProjected(host: LocalHost, command: HubCommand): Promise<unknown> {
  const result = await host.application.execute(command)
  return projectLegacyResult(result, host)
}

async function reapSessionState(host: LocalHost, sessionId?: string): Promise<void> {
  const scope = sessionId ? [sessionId] : undefined
  if (host.localSessions && !host.localSessions.needsReap(scope)) return
  await executeProjected(host, {
    kind: 'reapSessions',
    meta: host.commandMeta('cli'),
    sessionIds: scope
  })
}

async function getSessionResult(host: LocalHost, id: string, requestId?: string, typed = false): Promise<unknown> {
  const result = await host.application.execute({
    kind: 'getSession',
    meta: host.commandMeta('cli', requestId),
    sessionId: id
  })
  return typed ? result : projectLegacyResult(result, host)
}

function sessionState(value: unknown): { id: string; status: string } {
  const result = value as {
    data?: { session?: { id?: unknown; status?: unknown } }
    session?: { id?: unknown; status?: unknown }
  } | null
  const session = result?.data?.session || result?.session
  if (!session || typeof session.id !== 'string' || typeof session.status !== 'string') {
    throw new Error('session response is missing session state')
  }
  return { id: session.id, status: session.status }
}

async function waitUntilSettled(host: LocalHost, id: string, requestId?: string, typed = false): Promise<unknown> {
  const timeoutMs = Number(process.env.HUB_WAIT_TIMEOUT_MS || 30 * 60 * 1000)
  const started = Date.now()
  let nextRequestId = requestId
  for (;;) {
    await reapSessionState(host, id)
    const response = await getSessionResult(host, id, nextRequestId, typed)
    nextRequestId = undefined
    const session = sessionState(response)
    if (session.status !== 'running') return response
    if (Date.now() - started > timeoutMs) fail(`session ${id} still running after ${timeoutMs}ms`)
    await new Promise((resolve) => setTimeout(resolve, 250))
  }
}

function takeRunnerOptions(argv: string[]): SessionRequestOptions {
  const profile = takeFlag(argv, '--model')
  const quality = takeFlag(argv, '--effort')
  const noSpawn = takeSwitch(argv, '--no-spawn')
  const wait = takeSwitch(argv, '--wait')
  return { profile, quality, start: !noSpawn, wait }
}

const rawArgv = process.argv.slice(2)
const command = rawArgv[0] || ''
if (!command || command === '-h' || command === '--help') {
  process.stdout.write(`${usage()}\n`)
  process.exit(command ? 0 : 1)
}

const argv = rawArgv.slice(1)
const packageRoot = findHubRoot()

async function main() {
  const dataRoot = resolveLocalDataRoot({ packageRoot })
  if (command === 'setup' || command === 'install') {
    const flags = {
      dryRun: takeSwitch(argv, '--dry-run'),
      json: takeSwitch(argv, '--json'),
      noDaemon: takeSwitch(argv, '--no-daemon'),
      noPath: takeSwitch(argv, '--no-path'),
      noTask: takeSwitch(argv, '--no-task'),
      rebuild: takeSwitch(argv, '--rebuild')
    }
    const result = await setupHub(packageRoot, flags)
    if (flags.json) print(result)
    else process.stdout.write(`${formatSetupReport(result)}\n`)
    if (!result.ok) process.exit(1)
    return
  }
  if (command === 'uninstall') {
    const json = takeSwitch(argv, '--json')
    const result = await uninstallHub(packageRoot)
    if (json) print(result)
    else process.stdout.write(`${formatUninstallReport(result)}\n`)
    if (!result.ok) process.exit(1)
    return
  }
  if (command === 'doctor') {
    const json = takeSwitch(argv, '--json')
    const report = await doctorHub(packageRoot)
    if (json) print(report)
    else process.stdout.write(`${formatDoctorReport(report)}\n`)
    if (!report.ok) process.exit(1)
    return
  }
  if (command === 'daemon') {
    const sub = argv[0] || 'status'
    if (sub === 'run') {
      await runDaemon({ hubRoot: packageRoot, packageRoot, dataRoot })
      return
    }
    if (sub === 'start') {
      const started = await startDaemonDetached(packageRoot, undefined, dataRoot)
      print({ action: 'daemon-start', ...started })
      if (!started.ok) process.exit(1)
      return
    }
    if (sub === 'stop') {
      const stopped = stopDaemon(dataRoot, undefined, packageRoot)
      print({
        ok: stopped,
        action: 'daemon-stop',
        stopped,
        ...(stopped ? {} : {
          error: {
            code: 'DAEMON_INSTANCE_UNVERIFIED',
            message: 'daemon instance could not be verified stopped; lifecycle markers were preserved'
          }
        })
      })
      if (!stopped) process.exitCode = 1
      return
    }
    if (sub === 'status') {
      print(await daemonStatus(packageRoot, undefined, dataRoot))
      return
    }
    fail(`unknown daemon command: ${sub}\n${usage()}`)
  }

  const host = createLocalHost({ packageRoot, dataRoot })
  const requestId = takeFlag(argv, '--request-id')
  const contractV1 = takeSwitch(argv, '--contract-v1')
  const commandMeta = () => host.commandMeta('cli', requestId)
  const execute = async (typed: HubCommand) => {
    const result = await host.application.execute(typed)
    if (contractV1) {
      if (!result.ok) process.exitCode = 1
      return result
    }
    return projectLegacyResult(result, host)
  }

  if (command === 'status') {
    await reapSessionState(host)
    print(await execute({ kind: 'status', meta: commandMeta() }))
    return
  }
  if (command === 'list-worktrees') {
    print(await execute({ kind: 'listWorktrees', meta: commandMeta() }))
    return
  }
  if (command === 'list-skills') {
    print(await execute({ kind: 'listSkills', meta: commandMeta() }))
    return
  }
  if (command === 'inspect-schema') {
    requireNoArguments(argv, 'inspect-schema')
    print(await execute({ kind: 'inspectSchema', meta: commandMeta() }))
    return
  }
  if (command === 'snapshot') {
    const subcommand = argv.shift()
    if (subcommand === 'create') {
      requireNoArguments(argv, 'snapshot create')
      print(await execute({ kind: 'createSnapshot', meta: commandMeta() }))
      return
    }
    if (subcommand === 'list') {
      requireNoArguments(argv, 'snapshot list')
      print(await execute({ kind: 'listSnapshots', meta: commandMeta() }))
      return
    }
    if (subcommand === 'show') {
      const snapshotId = takeFlag(argv, '--id') as Sha256Identifier | undefined
      if (!snapshotId) fail('snapshot show requires --id')
      requireNoArguments(argv, 'snapshot show')
      print(await execute({ kind: 'getSnapshot', meta: commandMeta(), snapshotId }))
      return
    }
    fail('snapshot requires create, list, or show')
  }
  if (command === 'pin') {
    const subcommand = argv.shift()
    const worktree = takeFlag(argv, '--worktree')
    if (!worktree) fail(`pin ${subcommand || ''} requires --worktree`.replace('  ', ' '))
    if (subcommand === 'show') {
      requireNoArguments(argv, 'pin show')
      print(await execute({ kind: 'getPin', meta: commandMeta(), worktree }))
      return
    }
    if (subcommand === 'set') {
      const snapshotId = takeFlag(argv, '--snapshot') as Sha256Identifier | undefined
      const selectedSkills = takeRepeatedFlags(argv, '--skill')
      const clearSkills = takeSwitch(argv, '--clear-skills')
      if (!snapshotId) fail('pin set requires --snapshot')
      if (clearSkills && selectedSkills.length > 0) {
        fail('pin set accepts either --skill or --clear-skills, not both')
      }
      requireNoArguments(argv, 'pin set')
      print(await execute({
        kind: 'setPin',
        meta: commandMeta(),
        worktree,
        snapshotId,
        ...(clearSkills ? { selectedSkills: [] } : selectedSkills.length > 0 ? { selectedSkills } : {})
      }))
      return
    }
    fail('pin requires show or set')
  }
  if (command === 'migrate-state') {
    const dryRun = takeSwitch(argv, '--dry-run')
    const commit = takeSwitch(argv, '--commit')
    const planHash = takeFlag(argv, '--plan-hash') as Sha256Identifier | undefined
    if (dryRun === commit) fail('migrate-state requires exactly one of --dry-run or --commit')
    if (dryRun && planHash) fail('migrate-state --dry-run does not accept --plan-hash')
    if (commit && !planHash) fail('migrate-state --commit requires --plan-hash')
    requireNoArguments(argv, 'migrate-state')
    print(await execute({
      kind: 'migrateState',
      meta: commandMeta(),
      mode: dryRun ? 'dryRun' : 'commit',
      ...(planHash ? { planHash } : {})
    }))
    return
  }
  if (command === 'repair-links') {
    const worktree = takeFlag(argv, '--worktree')
    if (!worktree) fail('repair-links requires --worktree')
    print(await execute({ kind: 'repairLegacy', meta: commandMeta(), worktree }))
    return
  }
  if (command === 'apply-legacy-attach') {
    const worktree = takeFlag(argv, '--worktree')
    const sessionId = takeFlag(argv, '--session-id')
    const sourcePolicy = takeFlag(argv, '--source-policy') as 'requireMatch' | 'preferLibrary' | 'promoteFromWorktree' | undefined
    const visibility = takeFlag(argv, '--visibility') as 'disable' | 'preserve' | undefined
    const configureGit = takeSwitch(argv, '--configure-git')
    if (!worktree) fail('apply-legacy-attach requires --worktree')
    print(await execute({
      kind: 'applyLegacyAttach',
      meta: commandMeta(),
      worktree,
      sessionId,
      sourcePolicy,
      visibility,
      configureGit
    }))
    return
  }
  if (command === 'apply-legacy-detach') {
    const worktree = takeFlag(argv, '--worktree')
    const sessionId = takeFlag(argv, '--session-id')
    if (!worktree) fail('apply-legacy-detach requires --worktree')
    print(await execute({
      kind: 'applyLegacyDetach',
      meta: commandMeta(),
      worktree,
      sessionId
    }))
    return
  }
  if (command === 'ingest') {
    const gameRepo = takeFlag(argv, '--game-repo')
    const dispatch = takeSwitch(argv, '--dispatch')
    const dryRun = takeSwitch(argv, '--dry-run')
    const payload = readStdin()
    print(await execute({
      kind: 'ingest',
      meta: commandMeta(),
      gameRepo,
      payload,
      dispatch,
      dryRun
    }))
    return
  }
  if (command === 'decide') {
    const id = takeFlag(argv, '--id')
    const action = takeFlag(argv, '--action') as InboxDecisionAction | undefined
    const note = takeFlag(argv, '--note')
    const mergeTarget = takeFlag(argv, '--merge-target')
    if (!id || !action) fail('decide requires --id and --action')
    print(await execute({ kind: 'decide', meta: commandMeta(), id, action, note, mergeTarget }))
    return
  }
  if (command === 'session') {
    const id = takeFlag(argv, '--id')
    const wait = takeSwitch(argv, '--wait')
    if (!id) fail('session requires --id')
    if (contractV1 && !wait) {
      await reapSessionState(host, id)
      print(await execute({ kind: 'getSession', meta: commandMeta(), sessionId: id }))
      return
    }
    const response = wait
      ? await waitUntilSettled(host, id, requestId, contractV1)
      : await (async () => {
          await reapSessionState(host, id)
          return contractV1
            ? execute({ kind: 'getSession', meta: commandMeta(), sessionId: id })
            : getSessionResult(host, id, requestId)
        })()
    print(response)
    return
  }
  if (command === 'analyze') {
    const inboxId = takeFlag(argv, '--id')
    const intent = takeFlag(argv, '--intent') || 'Analyze queued inbox skill updates'
    const runner = takeRunnerOptions(argv)
    print(await execute({ kind: 'analyze', meta: commandMeta(), inboxId, intent, runner }))
    return
  }
  if (command === 'attach' || command === 'detach' || command === 'edit' || command === 'chat') {
    const worktree = takeFlag(argv, '--worktree')
    const skillPath = takeFlag(argv, '--path')
    const intent = takeFlag(argv, '--intent')
    const runner = takeRunnerOptions(argv)
    if ((command === 'attach' || command === 'detach') && !worktree) fail(`${command} requires --worktree`)
    if (command === 'attach') {
      print(await execute({ kind: 'attach', meta: commandMeta(), worktree: worktree as string, intent, runner }))
      return
    }
    if (command === 'detach') {
      print(await execute({ kind: 'detach', meta: commandMeta(), worktree: worktree as string, intent, runner }))
      return
    }
    if (command === 'edit') {
      if (!skillPath) fail('edit requires --path')
      print(await execute({ kind: 'edit', meta: commandMeta(), path: skillPath, intent, runner }))
      return
    }
    print(await execute({ kind: 'chat', meta: commandMeta(), worktree, intent, runner }))
    return
  }
  if (command === 'resume') {
    const id = takeFlag(argv, '--id')
    const message = takeFlag(argv, '--message')
    const runner = takeRunnerOptions(argv)
    if (!id || !message) fail('resume requires --id and --message')
    print(await execute({
      kind: 'resumeSession',
      meta: commandMeta(),
      sessionId: id,
      message,
      runner
    }))
    return
  }
  fail(`unknown command: ${command}\n${usage()}`)
}

main().catch((error) => {
  fail(error instanceof Error ? error.message : String(error))
})
