import type { JsonObject } from './common.js'

export const HUB_ERROR_CODES = [
  'UNSUPPORTED_CONTRACT_VERSION',
  'INVALID_COMMAND_META',
  'INVALID_ARGUMENT',
  'REQUEST_ID_REQUIRED',
  'REQUEST_ID_CONFLICT',
  'REQUEST_IN_PROGRESS',
  'NOT_FOUND',
  'WORKTREE_NOT_RECOGNIZED',
  'WORKTREE_BLOCKED',
  'WORKTREE_ALREADY_CLAIMED',
  'FIRST_ATTACH_SESSION_REQUIRED',
  'DETACH_SESSION_REQUIRED',
  'INVALID_INBOX_TRANSITION',
  'INVALID_PIN',
  'CONFLICT_DIRTY',
  'CONFLICT_EXTERNAL_LINK',
  'CONFLICT_CONTENT',
  'STATE_VERSION_UNSUPPORTED',
  'STATE_CORRUPT',
  'MIGRATION_REQUIRED',
  'MIGRATION_PLAN_STALE',
  'LOCK_BUSY',
  'LOCK_NOT_OWNED',
  'SNAPSHOT_NOT_FOUND',
  'SNAPSHOT_INVALID',
  'RUNNER_UNAVAILABLE',
  'PORT_FAILURE',
  'UNSUPPORTED_COMMAND',
  'INTERNAL_ERROR',
  'WORKTREE_NOT_CLAIMED',
  'MATERIALIZE_PLAN_STALE',
  'MATERIALIZATION_MARKER_INVALID',
  'RUNTIME_ASSET_NOT_FOUND',
  'RUNTIME_ASSET_INVALID',
  'LEGACY_MIGRATION_REQUIRED',
  'LEGACY_PLAN_STALE',
  'LEGACY_MIGRATION_NOT_FOUND',
  'LEGACY_ROLLBACK_CONFLICT',
  'CONFLICT_PATH',
  'UNSUPPORTED_LAYOUT'
] as const

export type HubErrorCode = (typeof HUB_ERROR_CODES)[number]

export type HubError = {
  code: HubErrorCode
  message: string
  retryable: boolean
  details?: JsonObject
}
